Adjust examples to use to_3d(axes=…)
API changed in d2cd928. Fixes:

  TypeError: to_3d() got an unexpected keyword argument 'plane'

when running the examples.